name: managed-endpoint-score
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - pytorch==1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
  # - cudatoolkit==10.2.89
  - pip
  - pip:
    - azureml-defaults
