$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pytorch-gpu-inference-env
version: 1
docker:
  image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
conda_file: file:../pytorch_conda/conda_score.yml